version: "3.9"

services:
    app:
        container_name: app
        build:
            target: release
            dockerfile: Dockerfile
            context: .
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        restart: on-failure
        volumes:
            - ./logs:/var/log/letovo-computers

    db:
        container_name: postgres
        image: postgres:15.0-bullseye
        command: >
            -c ssl=on 
            -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem 
            -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
        restart: unless-stopped
        ports:
            - ${PGPORT}:${PGPORT}
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${PGDATABASE}
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./db-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}" ]
            interval: 10s
            timeout: 5s
            retries: 5
